root@controller:~# cat debug.yml
---
- name: Debug Example - pleasesee
  hosts: all
  tasks:
     - name: Print debug message
       debug:
         msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"
